/*
 * This source file was generated by the Gradle 'init' task
 */
package esim;

public class HelloWorld {

    public static void main(String[] args) {
        // String hello = "Hello, World!";
        // System.out.println(hello);    

        // PrimitiveDataTypes pdt = new PrimitiveDataTypes();
        // pdt.demo();

        // DataTypeVar dtv = new DataTypeVar();
        // dtv.demo();

        ObjectDataTypes odt = new ObjectDataTypes();
        odt.demo();        
    }
}
